SELECT VISIT_RECORD.Vid, COUNT(TREATMENT_TEST_PROCEDURE.Tid)
    FROM VISIT_RECORD 
    JOIN TREATMENT_TEST_PROCEDURE ON VISIT_RECORD.Vid = TREATMENT_TEST_PROCEDURE.Vid
    GROUP BY VISIT_RECORD.Vid;

SELECT PATIENT.Pid, COUNT(VISIT_RECORD.Vid)
    FROM PATIENT 
    JOIN VISIT_RECORD ON VISIT_RECORD.Pid = PATIENT.Pid
    GROUP BY PATIENT.Pid;